import { addDays, format, startOfWeek } from "date-fns";
import type { DemoState } from "@/lib/types";

function d(offset: number, from = startOfWeek(new Date(), { weekStartsOn: 1 })): string {
  return format(addDays(from, offset), "yyyy-MM-dd");
}

export const ORG_ID = "org-demo";
export const DEMO_STORAGE_KEY = "reaper-demo-state-v3";
export const DEMO_SESSION_KEY = "reaper-demo-session";

export function createDemoSeed(): DemoState {
  const week = startOfWeek(new Date(), { weekStartsOn: 1 });

  return {
    organization: {
      id: ORG_ID,
      name: "Northwind Studio",
      share_enabled: false,
      share_token: null,
    },
    profiles: [
      {
        id: "profile-admin",
        organization_id: ORG_ID,
        email: "admin@northwind.demo",
        full_name: "Alex Morgan",
        role: "admin",
      },
      {
        id: "profile-manager",
        organization_id: ORG_ID,
        email: "manager@northwind.demo",
        full_name: "Sam Rivera",
        role: "manager",
      },
    ],
    clients: [
      {
        id: "client-1",
        organization_id: ORG_ID,
        name: "Harbor Retail",
        notes: "E-commerce redesign",
        color: "#3B82F6",
      },
      {
        id: "client-2",
        organization_id: ORG_ID,
        name: "Atlas Health",
        notes: "Patient portal",
        color: "#10B981",
      },
      {
        id: "client-3",
        organization_id: ORG_ID,
        name: "Internal",
        notes: "Ops and R&D",
        color: "#F59E0B",
      },
    ],
    projects: [
      {
        id: "proj-1",
        organization_id: ORG_ID,
        client_id: "client-1",
        name: "Harbor Storefront",
        status: "active",
        priority: 1,
        color: "#3B82F6",
        start_date: d(-14, week),
        end_date: d(60, week),
        budget_hours: 120,
        budget_amount: null,
        budget_mode: "hours",
        budget_monthly_reset: false,
        notes: "Mid-burn project",
      },
      {
        id: "proj-2",
        organization_id: ORG_ID,
        client_id: "client-2",
        name: "Atlas Portal",
        status: "active",
        priority: 2,
        color: "#10B981",
        start_date: d(-7, week),
        end_date: d(45, week),
        budget_hours: 80,
        budget_amount: null,
        budget_mode: "hours",
        budget_monthly_reset: false,
        notes: "Over-planned on purpose for demo",
      },
      {
        id: "proj-3",
        organization_id: ORG_ID,
        client_id: "client-3",
        name: "Platform R&D",
        status: "active",
        priority: 3,
        color: "#F59E0B",
        start_date: d(0, week),
        end_date: d(90, week),
        budget_hours: null,
        budget_amount: null,
        budget_mode: "none",
        budget_monthly_reset: false,
        notes: "Internal ? no budget",
      },
      {
        id: "proj-4",
        organization_id: ORG_ID,
        client_id: "client-1",
        name: "Harbor Ops Support",
        status: "on_hold",
        priority: 4,
        color: "#8B5CF6",
        start_date: d(14, week),
        end_date: d(75, week),
        budget_hours: null,
        budget_amount: 6000,
        budget_mode: "amount",
        budget_monthly_reset: false,
        notes: "Dollar budget",
      },
      {
        id: "proj-5",
        organization_id: ORG_ID,
        client_id: "client-2",
        name: "Atlas Retainer",
        status: "active",
        priority: 2,
        color: "#06B6D4",
        start_date: d(-30, week),
        end_date: d(90, week),
        budget_hours: 40,
        budget_amount: null,
        budget_mode: "hours",
        budget_monthly_reset: true,
        notes: "Monthly hours retainer",
      },
    ],
    milestones: [
      {
        id: "ms-1",
        organization_id: ORG_ID,
        project_id: "proj-1",
        name: "Design freeze",
        due_date: d(5, week),
        status: "upcoming",
      },
      {
        id: "ms-2",
        organization_id: ORG_ID,
        project_id: "proj-1",
        name: "Launch",
        due_date: d(40, week),
        status: "upcoming",
      },
      {
        id: "ms-3",
        organization_id: ORG_ID,
        project_id: "proj-2",
        name: "Beta",
        due_date: d(18, week),
        status: "upcoming",
      },
    ],
    holiday_calendars: [
      {
        id: "cal-us",
        organization_id: ORG_ID,
        name: "US Federal",
        region: "US",
      },
      {
        id: "cal-ca",
        organization_id: ORG_ID,
        name: "Canada Federal",
        region: "CA",
      },
    ],
    holiday_calendar_days: [
      {
        id: "calday-us-1",
        organization_id: ORG_ID,
        calendar_id: "cal-us",
        date: d(10, week),
        name: "Sample US holiday",
      },
      {
        id: "calday-us-2",
        organization_id: ORG_ID,
        calendar_id: "cal-us",
        date: d(25, week),
        name: "Sample US holiday 2",
      },
      {
        id: "calday-ca-1",
        organization_id: ORG_ID,
        calendar_id: "cal-ca",
        date: d(11, week),
        name: "Sample Canada holiday",
      },
    ],
    people: [
      {
        id: "person-1",
        organization_id: ORG_ID,
        profile_id: "profile-manager",
        name: "Sam Rivera",
        email: "sam@demo.reaper",
        role_title: "Design Lead",
        department: "Design",
        office: "Seattle",
        capacity_hours_week: 40,
        cost_rate: 75,
        bill_rate: 150,
        timezone: "America/Los_Angeles",
        holiday_calendar_id: "cal-us",
      },
      {
        id: "person-2",
        organization_id: ORG_ID,
        profile_id: null,
        name: "Jordan Lee",
        email: "jordan@demo.reaper",
        role_title: "Senior Engineer",
        department: "Engineering",
        office: "Seattle",
        capacity_hours_week: 40,
        cost_rate: 90,
        bill_rate: 175,
        timezone: "America/Los_Angeles",
        holiday_calendar_id: "cal-us",
      },
      {
        id: "person-3",
        organization_id: ORG_ID,
        profile_id: null,
        name: "Casey Nguyen",
        email: "casey@demo.reaper",
        role_title: "Product Designer",
        department: "Design",
        office: "Remote",
        capacity_hours_week: 32,
        cost_rate: 65,
        bill_rate: 140,
        timezone: "America/Denver",
        holiday_calendar_id: "cal-us",
      },
      {
        id: "person-4",
        organization_id: ORG_ID,
        profile_id: null,
        name: "Riley Chen",
        email: "riley@demo.reaper",
        role_title: "Engineer",
        department: "Engineering",
        office: "Austin",
        capacity_hours_week: 40,
        cost_rate: 70,
        bill_rate: 155,
        timezone: "America/Chicago",
        holiday_calendar_id: "cal-ca",
      },
      {
        id: "person-5",
        organization_id: ORG_ID,
        profile_id: null,
        name: "Morgan Blake",
        email: "morgan@demo.reaper",
        role_title: "PM",
        department: "Delivery",
        office: "Seattle",
        capacity_hours_week: 40,
        cost_rate: 80,
        bill_rate: 160,
        timezone: "America/Los_Angeles",
        holiday_calendar_id: "cal-us",
      },
    ],
    assignments: [
      {
        id: "asg-1",
        organization_id: ORG_ID,
        person_id: "person-1",
        project_id: "proj-1",
        start_date: d(0, week),
        end_date: d(4, week),
        hours_per_day: 6,
        allocation_pct: 75,
        status: "confirmed",
        recurrence: "none",
        recurrence_end_date: null,
        notes: "",
      },
      {
        id: "asg-2",
        organization_id: ORG_ID,
        person_id: "person-2",
        project_id: "proj-1",
        start_date: d(0, week),
        end_date: d(9, week),
        hours_per_day: 5,
        allocation_pct: 62,
        status: "confirmed",
        recurrence: "none",
        recurrence_end_date: null,
        notes: "",
      },
      {
        id: "asg-3",
        organization_id: ORG_ID,
        person_id: "person-2",
        project_id: "proj-2",
        start_date: d(0, week),
        end_date: d(11, week),
        hours_per_day: 4,
        allocation_pct: 50,
        status: "confirmed",
        recurrence: "none",
        recurrence_end_date: null,
        notes: "Overbooks Jordan this week",
      },
      {
        id: "asg-4",
        organization_id: ORG_ID,
        person_id: "person-3",
        project_id: "proj-2",
        start_date: d(0, week),
        end_date: d(14, week),
        hours_per_day: 6,
        allocation_pct: 94,
        status: "confirmed",
        recurrence: "none",
        recurrence_end_date: null,
        notes: "",
      },
      {
        id: "asg-5",
        organization_id: ORG_ID,
        person_id: "person-4",
        project_id: "proj-2",
        start_date: d(0, week),
        end_date: d(9, week),
        hours_per_day: 7,
        allocation_pct: 87,
        status: "confirmed",
        recurrence: "none",
        recurrence_end_date: null,
        notes: "Pushes Atlas over total budget",
      },
      {
        id: "asg-6",
        organization_id: ORG_ID,
        person_id: "person-4",
        project_id: "proj-3",
        start_date: d(7, week),
        end_date: d(18, week),
        hours_per_day: 4,
        allocation_pct: 50,
        status: "confirmed",
        recurrence: "none",
        recurrence_end_date: null,
        notes: "",
      },
      {
        id: "asg-7",
        organization_id: ORG_ID,
        person_id: "person-5",
        project_id: "proj-3",
        start_date: d(0, week),
        end_date: d(4, week),
        hours_per_day: 3,
        allocation_pct: 37,
        status: "confirmed",
        recurrence: "none",
        recurrence_end_date: null,
        notes: "",
      },
      {
        id: "asg-8",
        organization_id: ORG_ID,
        person_id: "person-1",
        project_id: "proj-4",
        start_date: d(14, week),
        end_date: d(18, week),
        hours_per_day: 4,
        allocation_pct: 50,
        status: "tentative",
        recurrence: "none",
        recurrence_end_date: null,
        notes: "Does not burn budget",
      },
      {
        id: "asg-9",
        organization_id: ORG_ID,
        person_id: "person-5",
        project_id: "proj-1",
        start_date: d(2, week),
        end_date: d(6, week),
        hours_per_day: 4,
        allocation_pct: 50,
        status: "confirmed",
        recurrence: "none",
        recurrence_end_date: null,
        notes: "",
      },
    ],
    leave_days: [
      {
        id: "leave-1",
        organization_id: ORG_ID,
        person_id: "person-3",
        date: d(2, week),
        kind: "vacation",
        status: "approved",
        hours_per_day: null, // Full Day
        notes: "Family trip",
      },
      {
        id: "leave-2",
        organization_id: ORG_ID,
        person_id: "person-3",
        date: d(3, week),
        kind: "vacation",
        status: "approved",
        hours_per_day: null,
        notes: "Family trip",
      },
      {
        id: "leave-3",
        organization_id: ORG_ID,
        person_id: "person-5",
        date: d(4, week),
        kind: "sick",
        status: "approved",
        hours_per_day: null,
        notes: "",
      },
      {
        id: "leave-4",
        organization_id: ORG_ID,
        person_id: "person-4",
        date: d(10, week),
        kind: "holiday",
        status: "approved",
        hours_per_day: null,
        notes: "",
      },
      {
        id: "leave-5",
        organization_id: ORG_ID,
        person_id: "person-1",
        date: d(10, week),
        kind: "holiday",
        status: "approved",
        hours_per_day: null,
        notes: "",
      },
      {
        id: "leave-6",
        organization_id: ORG_ID,
        person_id: "person-2",
        date: d(10, week),
        kind: "holiday",
        status: "approved",
        hours_per_day: null,
        notes: "",
      },
    ],
    sessionProfileId: null,
  };
}

