import { addDays, format, startOfWeek } from "date-fns";
import type { DemoState } from "@/lib/types";

function d(offset: number, from = startOfWeek(new Date(), { weekStartsOn: 1 })): string {
  return format(addDays(from, offset), "yyyy-MM-dd");
}

function dt(offset: number, from = startOfWeek(new Date(), { weekStartsOn: 1 })): string {
  return `${d(offset, from)}T09:00:00.000Z`;
}

export const ORG_ID = "org-demo";
export const DEMO_STORAGE_KEY = "reaper-demo-state-v4";
export const DEMO_SESSION_KEY = "reaper-demo-session";

export function createDemoSeed(): DemoState {
  const week = startOfWeek(new Date(), { weekStartsOn: 1 });

  return {
    organization: {
      id: ORG_ID,
      name: "Northwind Studio",
      share_enabled: false,
      share_token: null,
    },
    profiles: [
      {
        id: "profile-admin",
        organization_id: ORG_ID,
        email: "admin@northwind.demo",
        full_name: "Alex Morgan",
        role: "admin",
      },
      {
        id: "profile-manager",
        organization_id: ORG_ID,
        email: "manager@northwind.demo",
        full_name: "Sam Rivera",
        role: "manager",
      },
    ],
    clients: [
      {
        id: "client-1",
        organization_id: ORG_ID,
        name: "Harbor Retail",
        notes: "E-commerce redesign",
        color: "#3B82F6",
        status: "active",
      },
      {
        id: "client-2",
        organization_id: ORG_ID,
        name: "Atlas Health",
        notes: "Patient portal",
        color: "#10B981",
        status: "active",
      },
      {
        id: "client-3",
        organization_id: ORG_ID,
        name: "Internal",
        notes: "Ops and R&D",
        color: "#F59E0B",
        status: "active",
      },
    ],
    projects: [
      {
        id: "proj-1",
        organization_id: ORG_ID,
        client_id: "client-1",
        name: "Harbor Storefront",
        status: "active",
        priority: 1,
        color: "#3B82F6",
        start_date: d(-14, week),
        end_date: d(60, week),
        budget_hours: 120,
        budget_amount: null,
        budget_mode: "hours",
        budget_monthly_reset: false,
        notes: "Mid-burn project",
        share_enabled: true,
        share_token: "demo-harbor-storefront",
      },
      {
        id: "proj-2",
        organization_id: ORG_ID,
        client_id: "client-2",
        name: "Atlas Portal",
        status: "active",
        priority: 2,
        color: "#10B981",
        start_date: d(-7, week),
        end_date: d(45, week),
        budget_hours: 80,
        budget_amount: null,
        budget_mode: "hours",
        budget_monthly_reset: false,
        notes: "Over-planned on purpose for demo",
        share_enabled: false,
        share_token: null,
      },
      {
        id: "proj-3",
        organization_id: ORG_ID,
        client_id: "client-3",
        name: "Platform R&D",
        status: "active",
        priority: 3,
        color: "#F59E0B",
        start_date: d(0, week),
        end_date: d(90, week),
        budget_hours: null,
        budget_amount: null,
        budget_mode: "none",
        budget_monthly_reset: false,
        notes: "Internal ? no budget",
        share_enabled: false,
        share_token: null,
      },
      {
        id: "proj-4",
        organization_id: ORG_ID,
        client_id: "client-1",
        name: "Harbor Ops Support",
        status: "on_hold",
        priority: 4,
        color: "#8B5CF6",
        start_date: d(14, week),
        end_date: d(75, week),
        budget_hours: null,
        budget_amount: 6000,
        budget_mode: "amount",
        budget_monthly_reset: false,
        notes: "Dollar budget",
        share_enabled: false,
        share_token: null,
      },
      {
        id: "proj-5",
        organization_id: ORG_ID,
        client_id: "client-2",
        name: "Atlas Retainer",
        status: "active",
        priority: 2,
        color: "#06B6D4",
        start_date: d(-30, week),
        end_date: d(90, week),
        budget_hours: 40,
        budget_amount: null,
        budget_mode: "hours",
        budget_monthly_reset: true,
        notes: "Monthly hours retainer",
        share_enabled: false,
        share_token: null,
      },
    ],
    milestones: [
      {
        id: "ms-1",
        organization_id: ORG_ID,
        project_id: "proj-1",
        name: "Design freeze",
        due_date: d(5, week),
        status: "upcoming",
        client_approved: true,
      },
      {
        id: "ms-2",
        organization_id: ORG_ID,
        project_id: "proj-1",
        name: "Launch",
        due_date: d(40, week),
        status: "upcoming",
        client_approved: false,
      },
      {
        id: "ms-3",
        organization_id: ORG_ID,
        project_id: "proj-2",
        name: "Beta",
        due_date: d(18, week),
        status: "upcoming",
        client_approved: false,
      },
    ],
    holiday_calendars: [
      {
        id: "cal-us",
        organization_id: ORG_ID,
        name: "US Federal",
        region: "US",
      },
      {
        id: "cal-ca",
        organization_id: ORG_ID,
        name: "Canada Federal",
        region: "CA",
      },
    ],
    holiday_calendar_days: [
      {
        id: "calday-us-1",
        organization_id: ORG_ID,
        calendar_id: "cal-us",
        date: d(10, week),
        name: "Sample US holiday",
      },
      {
        id: "calday-us-2",
        organization_id: ORG_ID,
        calendar_id: "cal-us",
        date: d(25, week),
        name: "Sample US holiday 2",
      },
      {
        id: "calday-ca-1",
        organization_id: ORG_ID,
        calendar_id: "cal-ca",
        date: d(11, week),
        name: "Sample Canada holiday",
      },
    ],
    people: [
      {
        id: "person-1",
        organization_id: ORG_ID,
        profile_id: "profile-manager",
        name: "Sam Rivera",
        email: "sam@demo.reaper",
        role_title: "Design Lead",
        department: "Design",
        office: "Seattle",
        capacity_hours_week: 40,
        cost_rate: 75,
        bill_rate: 150,
        timezone: "America/Los_Angeles",
        holiday_calendar_id: "cal-us",
      },
      {
        id: "person-2",
        organization_id: ORG_ID,
        profile_id: null,
        name: "Jordan Lee",
        email: "jordan@demo.reaper",
        role_title: "Senior Engineer",
        department: "Engineering",
        office: "Seattle",
        capacity_hours_week: 40,
        cost_rate: 90,
        bill_rate: 175,
        timezone: "America/Los_Angeles",
        holiday_calendar_id: "cal-us",
      },
      {
        id: "person-3",
        organization_id: ORG_ID,
        profile_id: null,
        name: "Casey Nguyen",
        email: "casey@demo.reaper",
        role_title: "Product Designer",
        department: "Design",
        office: "Remote",
        capacity_hours_week: 32,
        cost_rate: 65,
        bill_rate: 140,
        timezone: "America/Denver",
        holiday_calendar_id: "cal-us",
      },
      {
        id: "person-4",
        organization_id: ORG_ID,
        profile_id: null,
        name: "Riley Chen",
        email: "riley@demo.reaper",
        role_title: "Engineer",
        department: "Engineering",
        office: "Austin",
        capacity_hours_week: 40,
        cost_rate: 70,
        bill_rate: 155,
        timezone: "America/Chicago",
        holiday_calendar_id: "cal-ca",
      },
      {
        id: "person-5",
        organization_id: ORG_ID,
        profile_id: null,
        name: "Morgan Blake",
        email: "morgan@demo.reaper",
        role_title: "PM",
        department: "Delivery",
        office: "Seattle",
        capacity_hours_week: 40,
        cost_rate: 80,
        bill_rate: 160,
        timezone: "America/Los_Angeles",
        holiday_calendar_id: "cal-us",
      },
    ],
    assignments: [
      {
        id: "asg-1",
        organization_id: ORG_ID,
        person_id: "person-1",
        project_id: "proj-1",
        start_date: d(0, week),
        end_date: d(4, week),
        hours_per_day: 6,
        allocation_pct: 75,
        status: "confirmed",
        recurrence: "none",
        recurrence_end_date: null,
        notes: "",
      },
      {
        id: "asg-2",
        organization_id: ORG_ID,
        person_id: "person-2",
        project_id: "proj-1",
        start_date: d(0, week),
        end_date: d(9, week),
        hours_per_day: 5,
        allocation_pct: 62,
        status: "confirmed",
        recurrence: "none",
        recurrence_end_date: null,
        notes: "",
      },
      {
        id: "asg-3",
        organization_id: ORG_ID,
        person_id: "person-2",
        project_id: "proj-2",
        start_date: d(0, week),
        end_date: d(11, week),
        hours_per_day: 4,
        allocation_pct: 50,
        status: "confirmed",
        recurrence: "none",
        recurrence_end_date: null,
        notes: "Overbooks Jordan this week",
      },
      {
        id: "asg-4",
        organization_id: ORG_ID,
        person_id: "person-3",
        project_id: "proj-2",
        start_date: d(0, week),
        end_date: d(14, week),
        hours_per_day: 6,
        allocation_pct: 94,
        status: "confirmed",
        recurrence: "none",
        recurrence_end_date: null,
        notes: "",
      },
      {
        id: "asg-5",
        organization_id: ORG_ID,
        person_id: "person-4",
        project_id: "proj-2",
        start_date: d(0, week),
        end_date: d(9, week),
        hours_per_day: 7,
        allocation_pct: 87,
        status: "confirmed",
        recurrence: "none",
        recurrence_end_date: null,
        notes: "Pushes Atlas over total budget",
      },
      {
        id: "asg-6",
        organization_id: ORG_ID,
        person_id: "person-4",
        project_id: "proj-3",
        start_date: d(7, week),
        end_date: d(18, week),
        hours_per_day: 4,
        allocation_pct: 50,
        status: "confirmed",
        recurrence: "none",
        recurrence_end_date: null,
        notes: "",
      },
      {
        id: "asg-7",
        organization_id: ORG_ID,
        person_id: "person-5",
        project_id: "proj-3",
        start_date: d(0, week),
        end_date: d(4, week),
        hours_per_day: 3,
        allocation_pct: 37,
        status: "confirmed",
        recurrence: "none",
        recurrence_end_date: null,
        notes: "",
      },
      {
        id: "asg-8",
        organization_id: ORG_ID,
        person_id: "person-1",
        project_id: "proj-4",
        start_date: d(14, week),
        end_date: d(18, week),
        hours_per_day: 4,
        allocation_pct: 50,
        status: "tentative",
        recurrence: "none",
        recurrence_end_date: null,
        notes: "Does not burn budget",
      },
      {
        id: "asg-9",
        organization_id: ORG_ID,
        person_id: "person-5",
        project_id: "proj-1",
        start_date: d(2, week),
        end_date: d(6, week),
        hours_per_day: 4,
        allocation_pct: 50,
        status: "confirmed",
        recurrence: "none",
        recurrence_end_date: null,
        notes: "",
      },
    ],
    leave_days: [
      {
        id: "leave-1",
        organization_id: ORG_ID,
        person_id: "person-3",
        date: d(2, week),
        kind: "vacation",
        status: "approved",
        hours_per_day: null, // Full Day
        notes: "Family trip",
      },
      {
        id: "leave-2",
        organization_id: ORG_ID,
        person_id: "person-3",
        date: d(3, week),
        kind: "vacation",
        status: "approved",
        hours_per_day: null,
        notes: "Family trip",
      },
      {
        id: "leave-3",
        organization_id: ORG_ID,
        person_id: "person-5",
        date: d(4, week),
        kind: "sick",
        status: "approved",
        hours_per_day: null,
        notes: "",
      },
      {
        id: "leave-4",
        organization_id: ORG_ID,
        person_id: "person-4",
        date: d(10, week),
        kind: "holiday",
        status: "approved",
        hours_per_day: null,
        notes: "",
      },
      {
        id: "leave-5",
        organization_id: ORG_ID,
        person_id: "person-1",
        date: d(10, week),
        kind: "holiday",
        status: "approved",
        hours_per_day: null,
        notes: "",
      },
      {
        id: "leave-6",
        organization_id: ORG_ID,
        person_id: "person-2",
        date: d(10, week),
        kind: "holiday",
        status: "approved",
        hours_per_day: null,
        notes: "",
      },
    ],
    project_assets: [
      {
        id: "asset-1",
        organization_id: ORG_ID,
        project_id: "proj-1",
        kind: "sow",
        label: "Statement of Work",
        url: "https://docs.example.com/harbor-sow",
        sort_order: 0,
      },
      {
        id: "asset-2",
        organization_id: ORG_ID,
        project_id: "proj-1",
        kind: "website",
        label: "Live site",
        url: "https://harbor-retail.example.com",
        sort_order: 1,
      },
      {
        id: "asset-3",
        organization_id: ORG_ID,
        project_id: "proj-1",
        kind: "figma",
        label: "Design file",
        url: "https://figma.com/file/harbor-storefront",
        sort_order: 2,
      },
      {
        id: "asset-4",
        organization_id: ORG_ID,
        project_id: "proj-1",
        kind: "staging",
        label: "Staging site",
        url: "https://staging.harbor.example.com",
        sort_order: 3,
      },
      {
        id: "asset-5",
        organization_id: ORG_ID,
        project_id: "proj-1",
        kind: "passwords",
        label: "Shared vault",
        url: "https://vault.example.com/harbor",
        sort_order: 4,
      },
    ],
    task_lists: [
      {
        id: "list-1",
        organization_id: ORG_ID,
        project_id: "proj-1",
        milestone_id: "ms-1",
        name: "Design freeze",
        color: "#FEF3C7",
        sort_order: 0,
      },
      {
        id: "list-2",
        organization_id: ORG_ID,
        project_id: "proj-1",
        milestone_id: "ms-2",
        name: "Launch",
        color: "#DBEAFE",
        sort_order: 1,
      },
      {
        id: "list-3",
        organization_id: ORG_ID,
        project_id: "proj-1",
        milestone_id: null,
        name: "Backlog",
        color: null,
        sort_order: 2,
      },
      {
        id: "list-4",
        organization_id: ORG_ID,
        project_id: "proj-5",
        milestone_id: null,
        name: "Retainer tasks",
        color: "#D1FAE5",
        sort_order: 0,
      },
    ],
    tasks: [
      {
        id: "task-1",
        organization_id: ORG_ID,
        project_id: "proj-1",
        list_id: "list-1",
        parent_id: null,
        assignee_person_id: "person-1",
        title: "Finalize homepage wireframes",
        status: "complete",
        start_date: d(-5, week),
        due_date: d(-2, week),
        notes: "",
        sort_order: 0,
      },
      {
        id: "task-2",
        organization_id: ORG_ID,
        project_id: "proj-1",
        list_id: "list-1",
        parent_id: null,
        assignee_person_id: "person-1",
        title: "Approve style guide",
        status: "active",
        start_date: d(0, week),
        due_date: d(3, week),
        notes: "Waiting on client sign-off",
        sort_order: 1,
      },
      {
        id: "task-3",
        organization_id: ORG_ID,
        project_id: "proj-1",
        list_id: "list-1",
        parent_id: "task-2",
        assignee_person_id: "person-1",
        title: "Collect stakeholder feedback",
        status: "active",
        start_date: d(0, week),
        due_date: d(2, week),
        notes: "",
        sort_order: 0,
      },
      {
        id: "task-4",
        organization_id: ORG_ID,
        project_id: "proj-1",
        list_id: "list-2",
        parent_id: null,
        assignee_person_id: "person-2",
        title: "Deploy to production",
        status: "upcoming",
        start_date: null,
        due_date: d(38, week),
        notes: "",
        sort_order: 0,
      },
      {
        id: "task-5",
        organization_id: ORG_ID,
        project_id: "proj-1",
        list_id: "list-2",
        parent_id: "task-4",
        assignee_person_id: "person-2",
        title: "Set up CI pipeline",
        status: "upcoming",
        start_date: null,
        due_date: d(35, week),
        notes: "",
        sort_order: 0,
      },
      {
        id: "task-6",
        organization_id: ORG_ID,
        project_id: "proj-1",
        list_id: "list-3",
        parent_id: null,
        assignee_person_id: null,
        title: "Explore upsell banner",
        status: "upcoming",
        start_date: null,
        due_date: null,
        notes: "Nice-to-have, not scoped yet",
        sort_order: 0,
      },
      {
        id: "task-7",
        organization_id: ORG_ID,
        project_id: "proj-5",
        list_id: "list-4",
        parent_id: null,
        assignee_person_id: "person-1",
        title: "Monthly design QA pass",
        status: "active",
        start_date: d(0, week),
        due_date: d(5, week),
        notes: "",
        sort_order: 0,
      },
      {
        id: "task-8",
        organization_id: ORG_ID,
        project_id: "proj-5",
        list_id: "list-4",
        parent_id: null,
        assignee_person_id: "person-2",
        title: "Patch dependency updates",
        status: "complete",
        start_date: d(-5, week),
        due_date: d(-3, week),
        notes: "",
        sort_order: 1,
      },
    ],
    task_comments: [
      {
        id: "comment-1",
        organization_id: ORG_ID,
        task_id: "task-2",
        author_profile_id: "profile-manager",
        body: "Let's lock this by Friday.",
        created_at: dt(1, week),
      },
      {
        id: "comment-2",
        organization_id: ORG_ID,
        task_id: "task-4",
        author_profile_id: "profile-admin",
        body: "Confirm DNS cutover window with client.",
        created_at: dt(2, week),
      },
    ],
    bulletins: [
      {
        id: "bulletin-1",
        organization_id: ORG_ID,
        project_id: "proj-1",
        title: "Kickoff recap posted",
        body: "Shared kickoff notes in the drive folder.",
        pinned: true,
        created_by_profile_id: "profile-admin",
        created_at: dt(-10, week),
      },
      {
        id: "bulletin-2",
        organization_id: ORG_ID,
        project_id: null,
        title: "Office closed Friday",
        body: "Team is off for the long weekend.",
        pinned: false,
        created_by_profile_id: "profile-manager",
        created_at: dt(-1, week),
      },
    ],
    project_templates: [
      {
        id: "template-1",
        organization_id: ORG_ID,
        name: "Web Build",
        description: "Standard website build milestones and tasks",
      },
    ],
    template_milestones: [
      {
        id: "tm-1",
        organization_id: ORG_ID,
        template_id: "template-1",
        name: "Discovery",
        offset_days: 7,
        sort_order: 0,
      },
      {
        id: "tm-2",
        organization_id: ORG_ID,
        template_id: "template-1",
        name: "Design freeze",
        offset_days: 21,
        sort_order: 1,
      },
      {
        id: "tm-3",
        organization_id: ORG_ID,
        template_id: "template-1",
        name: "Launch",
        offset_days: 60,
        sort_order: 2,
      },
    ],
    template_task_lists: [
      {
        id: "ttl-1",
        organization_id: ORG_ID,
        template_id: "template-1",
        template_milestone_id: "tm-1",
        name: "Discovery",
        sort_order: 0,
      },
      {
        id: "ttl-2",
        organization_id: ORG_ID,
        template_id: "template-1",
        template_milestone_id: "tm-2",
        name: "Design",
        sort_order: 1,
      },
      {
        id: "ttl-3",
        organization_id: ORG_ID,
        template_id: "template-1",
        template_milestone_id: "tm-3",
        name: "Launch",
        sort_order: 2,
      },
    ],
    template_tasks: [
      {
        id: "tt-1",
        organization_id: ORG_ID,
        template_id: "template-1",
        list_id: "ttl-1",
        parent_id: null,
        title: "Kickoff call",
        notes: "",
        offset_days: 1,
        sort_order: 0,
      },
      {
        id: "tt-2",
        organization_id: ORG_ID,
        template_id: "template-1",
        list_id: "ttl-1",
        parent_id: null,
        title: "Gather brand assets",
        notes: "",
        offset_days: 5,
        sort_order: 1,
      },
      {
        id: "tt-3",
        organization_id: ORG_ID,
        template_id: "template-1",
        list_id: "ttl-2",
        parent_id: null,
        title: "Wireframes",
        notes: "",
        offset_days: 14,
        sort_order: 0,
      },
      {
        id: "tt-4",
        organization_id: ORG_ID,
        template_id: "template-1",
        list_id: "ttl-2",
        parent_id: "tt-3",
        title: "Homepage wireframe",
        notes: "",
        offset_days: 12,
        sort_order: 0,
      },
      {
        id: "tt-5",
        organization_id: ORG_ID,
        template_id: "template-1",
        list_id: "ttl-3",
        parent_id: null,
        title: "QA pass",
        notes: "",
        offset_days: 55,
        sort_order: 0,
      },
      {
        id: "tt-6",
        organization_id: ORG_ID,
        template_id: "template-1",
        list_id: "ttl-3",
        parent_id: null,
        title: "Go live",
        notes: "",
        offset_days: 60,
        sort_order: 1,
      },
    ],
    sessionProfileId: null,
  };
}

